### ISSUE TITLE
When garmin's are off and no longer tracking, script still forward's packets

### ISSUE THREAD

**Issue by ericbrown** [kemenril/iR-APRSISD#3]
Using latest commit with 2 garmin's. 

I've had my Garmin's off for a couple hours now and I'm still getting packets forwarded to APRS every few minutes.  My APRS ID's:

https://aprs.fi/info/?call=N0EDB-12
https://aprs.fi/info/?call=N0EDB-13

Any thoughts on what's going on? I would think it would stop forwarding based on the fact that the time difference is so far off.

**Comment by kemenril** [comment]
I think maybe we should add lastUpdate to the list of globals in the sendAPRS function.  Not absolutely certain that's the problem,  but I'll take a look later.

**Comment by kemenril** [comment]
Actually just pushed a change with the correction.  Try it now.

**Comment by ericbrown** [comment]
Still forwarding old packets. 

To test: Turn on both devices -- and let one tracking point be sent on each device. Turn off tracking. The logging shows an incremental number being sent (and they continue to be transmitted to APRS).

Note: happens with only 1 device on and transmitting too.

<img width="526" alt="Screen Shot 2021-04-06 at 1 42 45 PM" src="https://user-images.githubusercontent.com/449599/113770605-8b11b900-96df-11eb-8420-419828a8e746.png">

**Comment by ericbrown** [comment]
another comment (and maybe a different bug):

Just had this message printed:

Can't process KML feed on this pass.
Traceback (most recent call last):
  File "./ir-aprsisd", line 359, in <module>
    for packet in getEvents():
TypeError: 'NoneType' object is not iterable

I can open another issue if needed.

**Comment by kemenril** [comment]
Definitely a different bug, but also fixed in the current revision.  The iteration over None was due to a design flaw in getEvents, which I had assumed would always return a list of (sometimes no) events, but then built to do otherwise.  The re-submission of packets already handled was due to a bad condition on an if statement.  Both are fixed, and at least appear to be working over here now.

Thanks for your help with this, by the way.  I should have caught either or both of these things, myself.  It doesn't matter how many devices you have going; I just hadn't really ran it for long enough since the changes to notice it happening.  Anyway, I won't close this yet, in case I'm mistaken, but I really think it should all be fixed.

**Comment by ericbrown** [comment]
Great, thanks.  

I'll grab the latest version and pull it down and test things out a bit more tomorrow.

**Comment by ericbrown** [comment]
It looks like its still forwarding packets to APRS.  The summary says it isn't, but APRS is still receiving an update every few minutes.

You can see aprs activity here: https://aprs.fi/?c=raw&call=N0EDB-12&limit=50&view=normal

I turned the device off around 9:20AM (ish) CDT but you can see the same packet forwarded after that. 

<img width="522" alt="Screen Shot 2021-04-08 at 9 56 24 AM" src="https://user-images.githubusercontent.com/449599/114059081-3ee68600-9851-11eb-852a-a5e4a410b8af.png">

**Comment by kemenril** [comment]
Well that's odd.  Is it updating both devices, or just the one with previous packets?  Also, I wonder hy the summary there isn't printing your IMEIs... tell me you're editing that out for display here and it's not somehow missing them.

**Comment by ericbrown** [comment]
Just the one that was on and running with packets (I didn't have the 2nd device on today)

**Comment by kemenril** [comment]
Well, mine isn't re-forwarding the old packet on a new start.  We'll have to wait a bit to get the tracker out and have it send some things.  Honestly, what you're describing is really strange considering the design.

The check to see whether the packet is new is right before the try block that sends an APRS packet, which is right before the packet count update.  If the check fails, the function returns immediately, and neither the packet count update nor the APRS packet should happen.  The APRS packet could throw an exception, and maybe not send an update while still having the incremented packet count.  I'm not sure how a packet count might miss an increase while still sending the packet, though.

... unless you're running another, older copy of the software somewhere as well at the same time.  I assume that's not the case. :)

**Comment by ericbrown** [comment]
Running the latest/greatest version. 

The only way to get it to stop forwarding the packet is to stop the deamon. Really strange.

**Comment by kemenril** [comment]
Just pushed a minor change that fixes some probably-unrelated but close enough to be interesting old bugs in handling of missed APRS packets, and added a bit of debugging to show more clearly what's happening.  If you don't mind, update it and try it again.  I'll do the same later in the day sometime when I find myself outside of a building.

**Comment by ericbrown** [comment]
Thanks. Just grabbed it and will check it out shortly with the inreach

**Comment by kemenril** [comment]
By the way, is it logging the IMEIs of the devices correctly on your machine?  Do you think I should add a configuration option to make it not do that?

**Comment by ericbrown** [comment]
it is logging the IMEI's correctly. I don't see any issue with current implementation (I've just been erasing info from screenshots when sharing)

**Comment by kemenril** [comment]
Just as long as we can be sure that it's actually always treating the same device as a particular SSID, it shouldn't matter for this. :)

**Comment by ericbrown** [comment]
I’m pretty sure it is...I haven’t seen any strangeness there.

**Comment by kemenril** [comment]
I might be speaking too soon, but after a quick trip outside to get some data going in, I don't appear to be able to get it to send extra packets when the device is stopped. Does it still do it for you after the last change?

**Comment by ericbrown** [comment]
I think I may have found the culprit.

I had a 2nd deamon running in `screen` that I didn't realize I had going.  It was running an old version. So...sorry for the headache :). 

I will test out the latest version again tonight but I am pretty sure it will work fine now.

**Comment by kemenril** [comment]
Ah, that would do it.  No problem.  I needed to review that section of the code and sort out what could/should actually happen in the case of exceptions during the APRS packet dispatch anyway.  Didn't find serious trouble, but I think it's more right now.

**Comment by ericbrown** [comment]
Cool. Will update with output from tests this evening

**Comment by ericbrown** [comment]
This looks to be fixed in latest version. The issue was the extra instance running in screen with an older version.

**Comment by kemenril** [comment]
Sounds good to me.  Note also a minor change in the past week that might make course/speed show up more consistently, though it shouldn't have any other effect.  In the previous versions, a device headed slowly north would have possibly shown up in APRS without the course/speed information. :)
